[theme]
primaryColor = "#e63946"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#1f2937"
textColor = "#ffffff"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
